---
- name: Install default docker
  hosts: linux_all
  become: yes

  tasks:
  - name: Install docker
    yum: name=docker-ce state=latest

  - name: Start nginx in docker
    shell: docker run -d -p 1234:80 nginx
...
